### ISSUE TITLE
Certain words will include kanji in the space intended for hiragana.

### ISSUE THREAD

**Issue by Eddy-Rogers** [Eddy-Rogers/JishoCSVExtension#4]
For Example:

馬鹿, [馬鹿ばか] idiot; moron; fool

**Comment by JosephBrooksbank** [comment]
For _some reason_, the furigana for this search was stored in a ruby text object??
anyway, it was including the kanji in it, because the kanji was also stored in the ruby object (in the furigana class) in a deprecated tag type. Very strange, and makes me think that some jisho entries are migrated from an older database or something.

Fixed in 8c190a0d6f4014a87f2448c2b49f4a54ebacd2d7
