### ISSUE TITLE
Searching certain kanji with no okurigana results in a null hiragana section.

### ISSUE THREAD

**Issue by Eddy-Rogers** [Eddy-Rogers/JishoCSVExtension#6]
For example, when I search 訴 instead of 訴える the hiragana section is null.

**Comment by JosephBrooksbank** [comment]
Now correctly outputs `訴える, [うったえる] to raise; to bring to (someone's attention)`

The issue came from Jisho's classification of 'exact match' vs 'concept', if the match isn't sure enough it assigns the class 'concept', which I originally filtered out. 

Fixed in e9c0984f7ab2a2d08614815e8fb0c0d7479bf12f
